/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
 /**
 *
 * @author RafikMedici
 */
import java.awt.Color;
import java.awt.Graphics;
import java.awt.Graphics2D;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;

public class GamePanel extends javax.swing.JFrame {
    Game game;
    
    /**
     * Creates new form GamePanel
     */
    
    public GamePanel() {
        super();
        this.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        this.setVisible(true);
        this.setLayout(null);
        this.setBounds(0, 0, 1000, 800);
        this.game = new Game();
        }
       

    public void paint(Graphics g) {
        Graphics2D g2 = (Graphics2D) g;
        for (int i = 0; Math.round(i) < 1000; i = i +  125) {
            for (int j = 0; Math.round(j) < 800; j = j +  100) {
                if (((i/125)+(j/100))%2==0) {
                    g2.setColor(Color.YELLOW);
                    g2.fillRoundRect(i, j, (125)-1, (125)-1, 25, 25);
                    g2.fillRoundRect(i, j, (100)-1, (100)-1, 25, 25);
                } else {
                    g2.setColor(Color.BLACK);
                    g2.fillRoundRect(i, j, (125)-1, (125)-1, 25, 25);
                    g2.fillRoundRect(i, j, (100)-1, (100)-1, 25, 25);
                }
            }
        }
        for (int i=0; Math.round(i) < 1000; i = i +  (125)){
            for (int j = 0; Math.round(j) < 250; j = j +  125){
                g.drawImage(game.gameboard[i*8/1000][j*8/1000].Occpie.img, i, j, null);
                System.out.println("done");
            }
        }
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 399, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 314, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) throws IOException {
        new GamePanel();
       
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
